TeamGuttok/back

.gitignore, docker-compose.yml, src/main/resources/application.properties, src/main/resources/application.yml
- docker-compose.yml 파일 추가 및 설정
- DB 환경 구성에 따른 application.yml 생성
- docker-compose 실행 시 생성되는 db 폴더 gitignore 설정
```bash
docker-compose up -d
docker-compose down
```
=> feat : Docker Compose 추가

build.gradle, src/main/java/com/app/guttokback/global/swagger/SwaggerConfig.java
Spring Docs의 Swagger을 추가했습니다
Spring Fox의 Swagger는 지원 종료라서 Docs 사용했습니다!
=> feat[#GUTTOK-3] : Spring Docs Swagger 추가

src/main/java/com/app/guttokback/subscription/domain/PaymentCycle.java, src/main/java/com/app/guttokback/subscription/domain/PaymentMethod.java, src/main/java/com/app/guttokback/subscription/domain/PaymentStatus.java, src/main/java/com/app/guttokback/subscription/domain/SubscriptionEntity.java, src/main/java/com/app/guttokback/subscription/domain/UserSubscriptionEntity.java
구독 서비스에 대한 Entity 구성입니다.
- Subscription - UserSubscriptionEntity `1:N 매핑`
- UserEntity - UserSubscriptionEntity `1:N 매핑`
- Enum Class 생성
- 결제 주기 `연, 월, 주, 일`
- 결제 방법 `카드, 계좌이체` → 추후 결제 방법에 대한 수정 필요
- 결제 상태 `결제 완료, 미결제`
- Enum Class에 String 반환 필드를 생성하였으나 이는 명시적인 용도이며 코드 작성 시 enum 값 그대로 사용하도록 하겠습니다. `ex) PaymentMethod.CARD`
`nullable = true`의 경우 default 설정 값 이지만 명시적으로 코드 작성 시 가독성을 위해 추가하였습니다!
=> Guttok 11 - 구독 서비스 Entity 구성

build.gradle, src/test/resources/application.yml
테스트 코드에서 사용 될 환경 설정하였습니다.
- Redis : localhost
- H2 : jdbc:h2:mem:test
- ddl-auto : create-drop
=> GUTTOK 24 - 테스트 코드 환경 설정

build.gradle
@RestControllerAdvice 어노테이션과 swagger 2.2.0 버전의 충돌
=> 2.7.0 버전 사용으로 해결
=> GUTTOK-25 : swagger 버전 오류 해결

.gitignore, build.gradle, src/main/java/com/app/guttokback/global/apiResponse/PageResponse.java, src/main/java/com/app/guttokback/global/queryDsl/QueryDslConfig.java, src/main/java/com/app/guttokback/subscription/controller/UserSubscriptionController.java, src/main/java/com/app/guttokback/subscription/dto/controllerDto/request/UserSubscriptionListRequest.java, src/main/java/com/app/guttokback/subscription/dto/controllerDto/response/UserSubscriptionListResponse.java, src/main/java/com/app/guttokback/subscription/dto/serviceDto/UserSubscriptionListInfo.java, src/main/java/com/app/guttokback/subscription/repository/UserSubscriptionQueryRepository.java, src/main/java/com/app/guttokback/subscription/service/UserSubscriptionService.java, src/test/java/com/app/guttokback/subscription/repository/UserSubscriptionQueryRepositoryTest.java, src/test/java/com/app/guttokback/subscription/service/UserSubscriptionServiceTest.java
- [GET] /api/subscriptions/{userId}?lastId=10&size=5
- 사이즈 요청 가능 `default size = 10`
- lastId(userSubscriptionId)는 nullable할 수 있다.
- lastId 기준 내림차순
- lastId 기준 다음에 보여줄 데이터 없을 시 `hasNext = false`
- 예외처리
- 회원이 존재하지 않을 시 
- 요청 size가 음수일 시
- 요청 lastId가 음수일 시
---
- ResponseBody
```json
{
"contents": [
{
"id": 9,
"title": "",
"subscription": "test",
"paymentAmount": 10000,
"paymentMethod": "BANK_TRANSFER",
"paymentCycle": "MONTHLY",
"paymentDay": 1,
"registerDate": "2024-12-27 00:17:36",
"updateDate": "2024-12-27 00:17:36"
},
{
"id": 8,
"title": "",
"subscription": "test",
"paymentAmount": 10000,
"paymentMethod": "BANK_TRANSFER",
"paymentCycle": "MONTHLY",
"paymentDay": 15,
"registerDate": "2024-12-27 00:09:40",
"updateDate": "2024-12-27 00:09:40"
},
{
"id": 7,
"title": "",
"subscription": …
```
=> Guttok 12 : 구독항목 리스트 조회 (사용자) API 구현

src/main/java/com/app/guttokback/global/apiResponse/ResponseMessages.java, src/main/java/com/app/guttokback/subscription/controller/UserSubscriptionController.java, src/main/java/com/app/guttokback/subscription/dto/serviceDto/SubscriptionListInfo.java, src/main/java/com/app/guttokback/subscription/service/UserSubscriptionService.java, src/test/java/com/app/guttokback/subscription/controller/UserSubscriptionControllerTest.java, src/test/java/com/app/guttokback/subscription/service/UserSubscriptionServiceTest.java
[GET] /api/subscriptions
- Enum클래스 code, name 응답
- ResponseBody
```json
{
"message": "구독 서비스 응답 성공",
"data": [
{
"code": "CUSTOM_INPUT",
"name": "직접 입력"
},
{
"code": "YOUTUBE_PREMIUM",
"name": "유튜브 프리미엄"
},
{
"code": "NETFLIX",
"name": "넷플릭스"
},
{
"code": "SPOTIFY",
"name": "스포티파이"
},
{
"code": "APPLE_MUSIC",
"name": "애플 뮤직"
},
{
"code": "COUPANG_WOW",
"name": "쿠팡 와우"
},
{
"code": "WAVVE",
"name": "웨이브"
},
{
"code": "WATCHA",
"name": "왓챠"
},
{
"code": "TVING",
"name": "티빙"
},
{
"code": "DISNEY_PLUS",
"name": "디즈니 플러스"
},
{
"code": "APPLE_TV",
"name": "애플 티비"
},
{
"code": "LAFTEL",
"name": "라프텔"
},
{
"code": "MELON",
"name": "멜론"
},
{
"code": "GENIE",
"name": "지니"
},
{
"code": "FLO",
"name": "플로"
},
{
"code": "AWS",
"name": "아마존 웹 서비스"
},
{
"code": "GCP",
"name": "구글 클라우드 플랫폼"
},
{
"code": …
```
=> Guttok 13 : 구독 서비스 리스트 조회 API 구현

src/main/java/com/app/guttokback/global/apiResponse/ResponseMessages.java, src/main/java/com/app/guttokback/global/aws/ses/controller/EmailController.java, src/main/java/com/app/guttokback/global/aws/ses/controller/FindPasswordController.java, src/main/java/com/app/guttokback/global/aws/ses/dto/controllerDto/UserEmailRequestDto.java, src/main/java/com/app/guttokback/global/aws/ses/dto/serviceDto/GetEmailDto.java, src/main/java/com/app/guttokback/global/aws/ses/service/EmailTemplateService.java, src/main/java/com/app/guttokback/global/aws/ses/service/FindPasswordService.java, src/main/java/com/app/guttokback/global/exception/ErrorCode.java, src/main/java/com/app/guttokback/global/redis/RedisConfig.java, src/main/java/com/app/guttokback/global/security/SecurityConfig.java, src/main/java/com/app/guttokback/user/controller/UserController.java, src/main/java/com/app/guttokback/user/dto/controllerDto/UserCertificationNumberRequestDto.java, src/main/java/com/app/guttokback/user/dto/serviceDto/GetCertificationNumberDto.java, src/main/java/com/app/guttokback/user/service/UserCertificationNumberService.java, src/main/resources/templates/CertificationNumber-email.html
http://localhost:8080/api/users/find-password (post)
비밀번호 찾기 인증코드 요청
```
// request
{
"email": "이메일@naver.com"
}
```
http://localhost:8080/api/users/certification-number (post)
인증코드 검증 요청
```
// request
{
"email": "이메일@naver.com",
"certificationNumber" : "LKLx"
}
```
인증코드를 통해 인증하면 로그인과 같은 session을 얻지만,
만료시간을 10분으로 지정해서 정해진 시간에 비밀번호 변경하지 못하면 다시 인증코드를 메일로 받아서 인증을 진행해야 합니다
=> Guttok 44 - 비밀번호 찾기 구현

src/main/java/com/app/guttokback/global/security/config/SecurityConfig.java, src/main/java/com/app/guttokback/global/security/role/Roles.java, src/main/java/com/app/guttokback/user/domain/UserEntity.java, src/main/java/com/app/guttokback/user/service/UserService.java, src/test/java/com/app/guttokback/user/controller/AuthControllerTest.java
user soft delete 변경 & 권한 추가했습니다
=> Guttok 47 -  user soft delete 변경

src/main/java/com/app/guttokback/subscription/controller/UserSubscriptionController.java, src/main/java/com/app/guttokback/subscription/dto/controllerDto/request/UserSubscriptionSaveRequest.java, src/main/java/com/app/guttokback/subscription/dto/serviceDto/UserSubscriptionSaveInfo.java, src/main/java/com/app/guttokback/subscription/service/UserSubscriptionService.java, src/test/java/com/app/guttokback/subscription/controller/UserSubscriptionControllerTest.java, src/test/java/com/app/guttokback/subscription/dto/controllerDto/request/UserSubscriptionSaveRequestTest.java, src/test/java/com/app/guttokback/subscription/service/UserSubscriptionServiceTest.java
구독항목 생성 API에 대해 로그인된 사용자 정보주입 적용하였습니다.
=> Guttok 53 : 구독항목 생성 로그인 사용자 정보주입 적용

src/main/java/com/app/guttokback/subscription/domain/PaymentMethod.java
=> Guttok 55 : 결제수단(PaymentMethod) 추가

src/main/java/com/app/guttokback/subscription/controller/UserSubscriptionController.java, src/main/java/com/app/guttokback/subscription/service/UserSubscriptionService.java, src/test/java/com/app/guttokback/subscription/controller/UserSubscriptionControllerTest.java, src/test/java/com/app/guttokback/subscription/service/UserSubscriptionServiceTest.java
구독항목 삭제에 대해 로그인 정보 주입 적용
삭제 시 본인이 생성한 구독항목이 아니면 예외 발생
=> Guttok 57 : 구독항목 삭제 로그인 정보 주입 적용

.gitignore, docker-compose.yml, src/main/resources/application.yml, src/test/resources/application.yml
env 파일 import하여 환경변수 사용하도록 설정하였습니다.
- application.yml
- application.yml (test)
- docker-compose.yml
=> Guttok 49 : env 환경변수 설정

src/test/java/com/app/guttokback/global/aws/ses/service/EmailTemplateServiceTest.java, src/test/java/com/app/guttokback/global/aws/ses/service/ReminderServiceTest.java
리마인더 관련 테스트코드 작성하였습니다.
혹시 이상한 부분이 있다면 말씀해주세요!
=> Guttok 58 : 리마인더 관련 테스트코드 작성

src/main/java/com/app/guttokback/global/apiResponse/ResponseMessages.java, src/main/java/com/app/guttokback/user/controller/AuthController.java, src/main/java/com/app/guttokback/user/service/SessionService.java
/api/users/check-session (get)
```
{
"message": "유효 세션",
"data": null,
"status": "OK"
}
```
세션 확인용이라 get mapping을 사용하였습니다
=> Guttok 59 - session 검증 구현

Dockerfile, docker-compose-build.yml, src/main/java/com/app/guttokback/global/dockerTest/TestController.java, src/main/java/com/app/guttokback/global/security/config/SecurityConfig.java
docker-compose-build.yml 에서 Docker file을 이용해 bootjar, MySQL, Redis 컨테이너 구축 하도록 했습니다
```
docker-compose -f docker-compose-build.yml up -d
```
-f 를 통해 시킬 파일을 구분할 수 있습니다
```
docker logs app
```
위 명령어를 이용하여 컨테이너에 들어있는 bootjar 파일 실행 로그를 확인할 수 있습니다
```
http://localhost:8080/hello (get)
```
동작 확인용 get api를 만들어서 정상 동작 시 hello를 반환하도록 했습니다
=> Guttok 46 - bootjar, MySQL, Redis 컨테이너 구축

src/main/java/com/app/guttokback/notification/domain/Category.java, src/main/java/com/app/guttokback/notification/domain/Message.java, src/main/java/com/app/guttokback/notification/domain/NotificationEntity.java, src/main/java/com/app/guttokback/notification/domain/Status.java
알림 정보에 대한 Entity 구성 추가하였습니다.
user-notification 1:N 매핑
현재까지 구성된 ERD이며, 그룹에 대해선 보류 상태로 두었습니다!
=> Guttok-73 : 알림 정보 Entity 구성

src/main/java/com/app/guttokback/global/aws/ses/service/ReminderService.java, src/main/java/com/app/guttokback/global/converter/EnumConverter.java, src/main/java/com/app/guttokback/notification/domain/Category.java, src/main/java/com/app/guttokback/notification/domain/Message.java, src/main/java/com/app/guttokback/notification/domain/NotificationEntity.java, src/main/java/com/app/guttokback/notification/repository/NotificationRepository.java, src/main/java/com/app/guttokback/notification/service/NotificationService.java, src/main/java/com/app/guttokback/user/service/UserService.java, src/test/java/com/app/guttokback/notification/service/NotificationServiceTest.java
회원 가입, 리마인더 이메일 발송 시 알림 정보 저장 로직 구현하였습니다.
메세지는 동적으로 처리되도록 하였습니다!
```text
tao님, 회원이 되신 것을 진심으로 환영합니다 🎉
tao님, 내일은 유튜브 프리미엄 결제일 입니다 💰
```
=> Guttok-75 : 알림 정보 저장 구현

.github/workflows/deploy.yml
pr은 모든 브랜치를 대상으로 동작 하도록 수정했고, main 이벤트는 refs/heads/main 조건만 사용하도록 수정했습니다
=> Guttok 81 : github actions 오류 수정

src/main/java/com/app/guttokback/global/security/config/SecurityConfig.java
- requestMatchers를 permitAll에서 authenticated로 변경했습니다
- corsFilter를 addFilter로 config에 추가했습니다
=> GUTTOK-83 : spring security config 수정

src/main/java/com/app/guttokback/global/aws/ses/controller/EmailController.java, src/main/java/com/app/guttokback/global/dockerTest/TestController.java, src/main/java/com/app/guttokback/group/controller/SubscriptionGroupController.java, src/main/java/com/app/guttokback/notification/controller/NotificationController.java, src/main/java/com/app/guttokback/subscription/controller/UserSubscriptionController.java, src/main/java/com/app/guttokback/user/controller/AuthController.java, src/main/java/com/app/guttokback/user/controller/UserController.java
전체적인 Controller 응답 클래스 수정과 Swagger 디테일 추가하였습니다.
=> GUTTOK-84 : Swagger 디테일 추가

src/main/java/com/app/guttokback/global/security/config/SecurityConfig.java
- user 관련 엔드포인트 `인증번호 요청, 이메일 검증, 세션 체크, 인증번호 이메일 발송` permitAll에 추가
- 회원 접근 권한체크
- 나머지 Request에 대한 authenticated 설정
=> GUTTOK-85 : SpringSecurity 권한 체크 수정

src/main/java/com/app/guttokback/user/controller/AuthController.java
swagger 설명 중 헷갈리게 작성되었던 인증번호 검증 부분 명확하게 알 수 있도록 수정하였습니다.
=> GUTTOK-88 : swagger 인증번호 검증 부분 설명 수정

docker-compose-build.yml, src/main/java/com/app/guttokback/user/service/UserCertificationNumberService.java
인증코드 검증 메소드에서 중복되는 session 설정을 분리하여 initializeUserSession 메서드로 만들었습니다
=> GUTTOK-87 : 사용자 세션 설정 initializeUserSession로 중복 분리

src/main/java/com/app/guttokback/group/controller/SubscriptionGroupController.java, src/main/java/com/app/guttokback/notification/controller/NotificationController.java, src/main/java/com/app/guttokback/subscription/controller/UserSubscriptionController.java, src/main/java/com/app/guttokback/user/controller/UserController.java, src/main/java/com/app/guttokback/user/domain/UserEntity.java, src/main/java/com/app/guttokback/user/service/SessionService.java
SessionService에 updateSessionTtl 메서드를 만들었습니다
api 동작 시 sessionService.updateSessionTtl();가 동작하여 sessino ttl을 1800으로 갱신할 수 있도록 했습니다
추가적으로 userEntity에 getAuthorities 메소드가 빈 리스트를 반환하고 있는 것을 확인하여 roles 리스트를 반환하도록 수정했습니다
=> GUTTOK-90 : session 만료 시간 갱신 구현

src/main/java/com/app/guttokback/common/infrastructure/config/CorsConfig.java, src/main/java/com/app/guttokback/common/infrastructure/config/SecurityConfig.java
corsConfig에 리액트 주소를 명시적으로 추가했고,  securityConfig에서 corsConfig 호출 방식을 변경했습니다
=> Guttok-95 : cors 오류 추가 수정

.github/workflows/deploy.yml
기존 컨테이너 중지 및 삭제에 docker image prune -af 명령어 추가
-a : 사용되지 않는 모든 이미지 삭제
-f: 확인 메세지 없이 강제 삭제
=> GUTTOK-96 : aws 미사용 이미지 삭제 추가

.github/workflows/deploy.yml, src/main/resources/application-aws.yml
=> GUTTOK-97 : redis 오류 해결

docker-compose.yml, src/main/java/com/app/guttokback/userSubscription/application/dto/controllerDto/response/UserSubscriptionListResponse.java
사용자 구독서비스 리스트 조회 시 `memo`에 대한 누락 값 추가하였습니다.
이번 pr올리며 환경변수 설정에 따른 docker-compose.yml 값 또한 수정하였습니다.
=> Guttok 98 - 사용자 구독서비스 리스트 조회 누락 값  추가

src/main/java/com/app/guttokback/common/scheduler/SchedulerTask.java
프론트 요청으로 테스트 데이터를 위한 scheduler 주석 해제
=> GUTTOK-99 : 테스트 데이터를 위한 scheduler 주석 해제

src/main/java/com/app/guttokback/common/scheduler/SchedulerTask.java
=> GUTTOK100 : 테스트 push

src/main/java/com/app/guttokback/common/infrastructure/config/CorsConfig.java
=> GUTTOK-102 : 운영 사이트 cors 설정 추가

.github/workflows/deploy.yml
운영서버에서 프론트 서버와의 통신을 위해 nginx 설정 추가 하였습니다
=> GUTTOK-103 : CI/CD nginx 설정 추가

src/main/java/com/app/guttokback/common/infrastructure/config/SecurityConfig.java
서브 도메인에서도 모두 사용 가능하도록 쿠키 도메인 설정 추가하였습니다.
=> GUTTOK-110 : 쿠키 도메인 설정 추가

src/main/resources/application-aws.yml, src/main/resources/application.yml
```
session:
cookie:
domain: guttok.site
```
을 apprication-aws.yml에 추가
=> GUTTOK-111 : 도메인 설정 추가

src/main/resources/application-aws.yml, src/main/resources/application.yml
=> GUTTOK-111 : 도메인 관련 주석 제거

src/main/java/com/app/guttokback/userSubscription/domain/repository/UserSubscriptionQueryRepository.java
유저에 대한 구독항목 리스트가 정상적으로 조회되지 않아 조회쿼리 수정하였습니다
=> GUTTOK-112 : userSubscription List 조회 쿼리 수정

src/main/java/com/app/guttokback/user/application/dto/controllerDto/UserSaveRequest.java, src/main/java/com/app/guttokback/user/application/dto/serviceDto/UserSaveInfo.java, src/main/java/com/app/guttokback/user/application/service/UserService.java, src/main/java/com/app/guttokback/user/domain/entity/User.java
유저 테이블에 약관 동의 항목을 추가했습니다
```
@Column(nullable = false)
@Comment("약관 동의")
private boolean policyConsent;
```
=> GUTTOK-121 : 약관 동의 추가

src/main/java/com/app/guttokback/common/converter/EnumConverter.java, src/main/java/com/app/guttokback/user/domain/entity/User.java, src/main/resources/application-aws.yml
role enum converter 추가하고, @Enumerated(EnumType.STRING)제거, aws-application.yml에  ddl-auto: validate로 변경 했습니다
=> Guttok-122 : role enum 설정 수정
