src/main/java/com/app/guttokback/global/apiResponse/ResponseMessages.java
src/main/java/com/app/guttokback/global/exception/ErrorCode.java
src/main/java/com/app/guttokback/subscription/controller/UserSubscriptionController.java
src/main/java/com/app/guttokback/subscription/domain/SubscriptionEntity.java
src/main/java/com/app/guttokback/subscription/domain/UserSubscriptionEntity.java
src/main/java/com/app/guttokback/subscription/dto/controllerDto/request/UserSubscriptionSaveRequest.java
src/main/java/com/app/guttokback/subscription/dto/serviceDto/UserSubscriptionSaveInfo.java
src/main/java/com/app/guttokback/subscription/repository/SubscriptionRepository.java
src/main/java/com/app/guttokback/subscription/repository/UserSubscriptionRepository.java
src/main/java/com/app/guttokback/subscription/service/UserSubscriptionService.java
src/test/java/com/app/guttokback/subscription/dto/controllerDto/request/UserSubscriptionSaveRequestTest.java
src/test/java/com/app/guttokback/subscription/service/UserSubscriptionServiceTest.java

- 예외 처리
- 필수 값 미 입력 시
- 구독 서비스 미 존재 시
- 생성하고자 하는 회원 미 존재 시
- 결제일자 Min 1, Max 31 외의 숫자 입력 시
- 첫 납부 날짜 `LocalDate` 타입이 아닐 시 yyyy-MM-dd (하이픈 포함)
- 회원 ID, 구독 서비스 ID, 납부 금액 음수일 시
- subscriptionId 1L = 직접 입력
- 결제 주기 PaymentCycle `Enum`
- `YEARLY("연")`, `MONTHLY("월")`, `WEEKLY("주")`, `DAILY("일")`;
- 결제 방법 PaymentMethod `Enum`
- `CARD("카드")`, `BANK_TRANSFER("계좌이체")`
- 결제 상태 PaymentStatus `Enum`
- `COMPLETED("결제 완료")`, `PENDING("미결제")`
- RequestBody
```json
{
"userId": 1,
"title": "",
"subscriptionId": 1,
"paymentAmount": 10000,
"paymentMethod": "BANK_TRANSFER",
"startDate": "2024-12-27",
"paymentCycle": "MONTHLY",
"paymentDay": 15,
"memo": ""
}
```
- ResponseBody
```json
{
"message": "구독항목 저장 성공",
"data": null,
"status": "OK"
}
```
이후 title, memo null 값 비 허용하여 빈값("") 요청 유도할지에 대한 고민이 필요합니다!

GUTTOK 14 - 구독 서비스 생성 API 구현

---

src/main/java/com/app/guttokback/global/apiResponse/ResponseMessages.java
src/main/java/com/app/guttokback/global/exception/ErrorCode.java
src/main/java/com/app/guttokback/global/security/SecurityConfig.java
src/main/java/com/app/guttokback/subscription/controller/UserSubscriptionController.java
src/main/java/com/app/guttokback/subscription/domain/UserSubscriptionEntity.java
src/main/java/com/app/guttokback/subscription/dto/controllerDto/request/UserSubscriptionUpdateRequest.java
src/main/java/com/app/guttokback/subscription/dto/serviceDto/UserSubscriptionUpdateInfo.java
src/main/java/com/app/guttokback/subscription/service/SubscriptionService.java
src/main/java/com/app/guttokback/subscription/service/UserSubscriptionService.java
src/test/java/com/app/guttokback/subscription/controller/UserSubscriptionControllerTest.java
src/test/java/com/app/guttokback/subscription/service/UserSubscriptionServiceTest.java

[PUT] /api/subscriptions/{id}
- 구독항목 미 존재시 예외처리
RequestBody
```json
{
"title": "제목 수정",
"paymentAmount": 15000,
"paymentMethod": "CARD",
"startDate": "2025-01-01",
"paymentCycle": "MONTHLY",
"paymentDay": 18,
"memo": "메모"
}
```
ResponseBody
```json
{
"message": "구독항목 수정 성공",
"data": null,
"status": "OK"
}
```

Guttok 15 : 사용자 구독항목 수정 API 구현

---

src/main/java/com/app/guttokback/global/apiResponse/ResponseMessages.java
src/main/java/com/app/guttokback/subscription/controller/UserSubscriptionController.java
src/main/java/com/app/guttokback/subscription/service/UserSubscriptionService.java
src/test/java/com/app/guttokback/subscription/controller/UserSubscriptionControllerTest.java
src/test/java/com/app/guttokback/subscription/service/UserSubscriptionServiceTest.java

[DELETE] /api/subscriptions/{id}
- 구독항목 미존재 시 예외처리
- ResponseBody
```json
{
"message": "구독항목 삭제 성공",
"data": null,
"status": "OK"
}
```

Guttok 16 : 사용자 구독항목 삭제 API 구현

---

build.gradle
src/main/java/com/app/guttokback/global/apiResponse/ResponseMessages.java
src/main/java/com/app/guttokback/global/aws/ses/config/SesConfig.java
src/main/java/com/app/guttokback/global/aws/ses/config/TemplateConfig.java
src/main/java/com/app/guttokback/global/aws/ses/controller/EmailController.java
src/main/java/com/app/guttokback/global/aws/ses/dto/EmailInfo.java
src/main/java/com/app/guttokback/global/aws/ses/dto/SubscriptionTotalAmountInfo.java
src/main/java/com/app/guttokback/global/aws/ses/service/EmailService.java
src/main/java/com/app/guttokback/global/aws/ses/service/EmailTemplateService.java
src/main/java/com/app/guttokback/global/aws/ses/service/RemainderService.java
src/main/java/com/app/guttokback/subscription/repository/UserSubscriptionQueryRepository.java
src/main/resources/application.yml
src/main/resources/templates/reminder-email.html
src/test/resources/application.yml

[POST] /api/mail/reminder `임시 컨트롤러로 스케줄러 구현 후 제거예정입니다.`
- 이메일 전송 실패 시 log.error로 에러 로그 출력 (exception 처리X)
- `alram = true`인 사용자에게만 이메일 전송
- HTML 템플릿을 사용하여 이메일 데이터 동적 처리 `템플릿 경로 : ./resources/templates`

Guttok 33 : 결제 리마인드 이메일 발송 기능 구현

---

src/main/java/com/app/guttokback/global/exception/CustomExceptionResponse.java
src/main/java/com/app/guttokback/global/exception/ErrorCode.java
src/main/java/com/app/guttokback/global/exception/GlobalExceptionHandler.java

에러 식별 코드 추가
// 기존 코드
```
//user
ID_NOT_FOUND(HttpStatus.BAD_REQUEST, "회원을 찾을 수 없습니다"),
EMAIL_SAME_FOUND(HttpStatus.CONFLICT, "중복된 회원이 존재합니다"),
NICKNAME_SAME_FOUND(HttpStatus.CONFLICT, "중복된 이름이 존재합니다")
```
// 식별 코드 추가
```
//user
ID_NOT_FOUND(HttpStatus.BAD_REQUEST, "USER_01", "회원을 찾을 수 없습니다"),
EMAIL_SAME_FOUND(HttpStatus.CONFLICT, "USER_02", "중복된 회원이 존재합니다"),
NICKNAME_SAME_FOUND(HttpStatus.CONFLICT, "USER_03", "중복된 이름이 존재합니다"),
```

Guttok 43 : 에러 식별 코드 추가

---

src/main/java/com/app/guttokback/global/exception/ErrorCode.java
src/main/java/com/app/guttokback/subscription/controller/UserSubscriptionController.java
src/main/java/com/app/guttokback/subscription/domain/UserSubscriptionEntity.java
src/main/java/com/app/guttokback/subscription/dto/controllerDto/request/UserSubscriptionSaveRequest.java
src/main/java/com/app/guttokback/subscription/dto/controllerDto/request/UserSubscriptionUpdateRequest.java
src/main/java/com/app/guttokback/subscription/dto/controllerDto/response/UserSubscriptionListResponse.java
src/main/java/com/app/guttokback/subscription/dto/serviceDto/UserSubscriptionSaveInfo.java
src/main/java/com/app/guttokback/subscription/dto/serviceDto/UserSubscriptionUpdateInfo.java
src/main/java/com/app/guttokback/subscription/service/UserSubscriptionService.java
src/test/java/com/app/guttokback/subscription/controller/UserSubscriptionControllerTest.java
src/test/java/com/app/guttokback/subscription/dto/controllerDto/request/UserSubscriptionSaveRequestTest.java
src/test/java/com/app/guttokback/subscription/repository/UserSubscriptionQueryRepositoryTest.java
src/test/java/com/app/guttokback/subscription/service/UserSubscriptionServiceTest.java

- 구독항목 수정에 대해 로그인 정보 주입 적용
- 수정 시 본인이 생성한 구독항목이 아니면 예외 발생
- startDate 필드 제거

Guttok 54 : 구독항목 수정 로그인 정보 주입 적용, startDate 필드 제거

---

src/main/java/com/app/guttokback/global/apiResponse/ResponseMessages.java
src/main/java/com/app/guttokback/global/aws/ses/controller/EmailController.java
src/main/java/com/app/guttokback/global/aws/ses/service/CertificationService.java
src/main/java/com/app/guttokback/global/exception/ErrorCode.java
src/main/java/com/app/guttokback/user/controller/AuthController.java
src/main/java/com/app/guttokback/user/controller/UserController.java
src/main/java/com/app/guttokback/user/service/UserCertificationNumberService.java
src/main/java/com/app/guttokback/user/service/UserService.java
src/main/resources/templates/CertificationNumber-email.html
src/test/java/com/app/guttokback/user/controller/UserControllerTest.java

http://localhost:8080/api/users/email-verification (post)
// 인증번호 검증
```
{
"email": "jucheol9877@naver.com",
"certificationNumber" : "oFoO7J"
}
```
http://localhost:8080/api/mail/certification (post)
// 인증번호 이메일로 요청
```
{
"email": "jucheol9877@naver.com"
}
```
동작 로직
1. 회원가입 시 이메일을 입력하고 이메일 검증 버튼 클릭
2. http://localhost:8080/api/mail/certification 가 동작해서 이메일로 인증코드 전송
3. http://localhost:8080/api/users/email-verification을 이용해서 인증번호가 맞다면 세션 반환
4. sinup을 진행하면서 이메일, 닉네임 등과 같은 정보와 세션을 함께 반환 (세션 10분 후 만료)
5. 세션이 일치한다면 정상적으로 회원가입 진행

Guttok 50 - 회원가입 이메일 인증 구현

---

src/main/java/com/app/guttokback/group/domain/GroupMemberEntity.java
src/main/java/com/app/guttokback/group/domain/SubscriptionGroupEntity.java

구독서비스 그룹 Entity 연관관계 매핑하여 추가하였습니다.
groups의 경우 MySQL 예약어로 되어있어 subscription_groups로 생성하였습니다.
그룹장 역할로 그룹 생성 시 생성한 사용자의 id를 받아 사용할 수 있도록 매핑하였습니다.
users - subscription_groups 1:N
users - group_members 1:N
subscription_groups - group_members 1:N
현재까지 생성된 ERD는 다음과 같습니다.

Guttok-62 : 구독서비스 그룹 Entity 추가

---

src/main/java/com/app/guttokback/global/apiResponse/ResponseMessages.java
src/main/java/com/app/guttokback/global/exception/ErrorCode.java
src/main/java/com/app/guttokback/group/controller/SubscriptionGroupController.java
src/main/java/com/app/guttokback/group/domain/GroupMemberEntity.java
src/main/java/com/app/guttokback/group/domain/SubscriptionGroupEntity.java
src/main/java/com/app/guttokback/group/dto/controllerDto/SubscriptionGroupSaveRequest.java
src/main/java/com/app/guttokback/group/dto/serviceDto/SubscriptionGroupSaveInfo.java
src/main/java/com/app/guttokback/group/repository/GroupMemberRepository.java
src/main/java/com/app/guttokback/group/repository/SubscriptionGroupRepository.java
src/main/java/com/app/guttokback/group/service/GroupMemberService.java
src/main/java/com/app/guttokback/group/service/SubscriptionGroupService.java
src/test/java/com/app/guttokback/group/controller/SubscriptionGroupControllerTest.java
src/test/java/com/app/guttokback/group/repository/GroupMemberRepositoryTest.java
src/test/java/com/app/guttokback/group/service/GroupMemberServiceTest.java
src/test/java/com/app/guttokback/group/service/SubscriptionGroupServiceTest.java

[POST] /api/groups
- **그룹 생성 API** 구현
- 그룹 생성 시 `title` (그룹 명)은 필수 입력값으로 처리
- 그룹 생성 시 생성자 (유저) 정보를 그룹장으로 저장
- 그룹 생성 후 `group_members` 테이블에 그룹과 유저 정보 매핑
- 예외 처리
- 필수 값 미입력 시 `400 Bad Request`
- 비로그인 시
- 회원을 찾을 수 없을 시 `404 Not Found`
- 이미 참가한 그룹에 참가 시 `409 Conflict`
- 그룹 생성 시 `SubscriptionGroupEntity`와 `GroupMemberEntity`를 생성하여, 그룹과 유저 정보를 DB에 저장
- 유효성 검사를 통해 필수 값을 체크하고, 중복 참가를 방지
- 그룹 생성 후, `group_members` 테이블에 유저와 그룹을 매핑하여 저장
- 일반 구독항목 생성과는 별개로 `title(그룹명), subscription(구독서비스)`필수 입력
- 예외 처리에 대한 테스트 코드 추가
- 필수 값 미입력 시, 회원 미존재 시, 중복 참가 시에 대한 검증
- 정상적인 그룹 생성 및 매핑 여부를 확인하는 테스트 코드 작성
```json
{
"title": "테스트 그룹",
"subscription": "YOUTUBE_PREMIUM",
"paymentAmount": 10000,
"paymentMethod": "BANK_TRANSFER",
"paymentCycle": "MONTHLY",
"paymentDay": 20,
"notice": "공지입니다."
}
```
```json
{
"message": …
```

Guttok 63 : 구독서비스 그룹 생성 API 구현

---

src/main/java/com/app/guttokback/global/exception/ErrorCode.java
src/main/java/com/app/guttokback/global/exception/GlobalExceptionHandler.java

바인드 에러, json 에러, 엔드포인트 에러, 서버에러에 대한 ExceptionHandler 추가하였습니다.
```json
// bind error
{
"errorCode": "BAD_REQUEST_ERROR",
"message": "결제일자는 1 이상이어야 합니다.",
"code": 400
}
```
```json
// json error
{
"errorCode": "JSON_ERROR",
"message": "paymentDay 필드 값이 잘못되었습니다. [int] 타입이어야 합니다.",
"code": 400
}
```
```json
// endpoint error
{
"errorCode": "ENDPOINT_ERROR",
"message": "잘못된 요청입니다.",
"code": 404
}
```
```json
// server error
{
"errorCode": "SERVER_ERROR",
"message": "서버 내부 오류가 발생했습니다.",
"code": 500
}
```

GUTTOK-71 : ExceptionHandler 추가

---

src/main/java/com/app/guttokback/global/apiResponse/util/PageOption.java
src/main/java/com/app/guttokback/global/apiResponse/util/PageRequest.java
src/main/java/com/app/guttokback/notification/controller/NotificationController.java
src/main/java/com/app/guttokback/notification/controller/notificationController.java
src/main/java/com/app/guttokback/notification/dto/controllerDto/response/NotificationListResponse.java
src/main/java/com/app/guttokback/notification/repository/NotificationQueryRepository.java
src/main/java/com/app/guttokback/notification/service/NotificationService.java
src/main/java/com/app/guttokback/subscription/controller/UserSubscriptionController.java
src/main/java/com/app/guttokback/subscription/repository/UserSubscriptionQueryRepository.java
src/main/java/com/app/guttokback/subscription/service/UserSubscriptionService.java
src/test/java/com/app/guttokback/notification/controller/NotificationControllerTest.java
src/test/java/com/app/guttokback/notification/service/NotificationServiceTest.java
src/test/java/com/app/guttokback/subscription/controller/UserSubscriptionControllerTest.java
src/test/java/com/app/guttokback/subscription/repository/UserSubscriptionQueryRepositoryTest.java
src/test/java/com/app/guttokback/subscription/service/UserSubscriptionServiceTest.java

[GET] /api/notifications?lastId=1&size=10
- 사이즈 요청 가능 default size = 10
- lastId(notificationId)는 nullable할 수 있다.
- lastId 기준 내림차순
- lastId 기준 다음에 보여줄 데이터 없을 시 hasNext = false
```json
{
"contents": [
{
"id": 5,
"category": "REMINDER",
"message": "구똑님, 내일은 테스트 결제일 입니다 💰",
"status": "UNREAD",
"registerDate": "2025-02-04 19:06:44",
"updateDate": "2025-02-04 19:06:44"
},
{
"id": 4,
"category": "REMINDER",
"message": "구똑님, 내일은 유튜브 프리미엄 결제일 입니다 💰",
"status": "UNREAD",
"registerDate": "2025-02-04 19:06:44",
"updateDate": "2025-02-04 19:06:44"
}
],
"size": 10,
"hasNext": false
}
```

Guttok 76 : 알림 조회 API 구현

---

src/main/java/com/app/guttokback/global/apiResponse/ResponseMessages.java
src/main/java/com/app/guttokback/global/exception/GlobalExceptionHandler.java
src/main/java/com/app/guttokback/notification/controller/NotificationController.java
src/main/java/com/app/guttokback/notification/domain/NotificationEntity.java
src/main/java/com/app/guttokback/notification/repository/NotificationQueryRepository.java
src/main/java/com/app/guttokback/notification/service/NotificationService.java
src/test/java/com/app/guttokback/notification/controller/NotificationControllerTest.java
src/test/java/com/app/guttokback/notification/repository/NotificationQueryRepositoryTest.java
src/test/java/com/app/guttokback/notification/service/NotificationServiceTest.java

[PUT] /api/notifications
- 해당 api 요청 시 요청한 회원의 읽지않음(UNREAD)상태의 알림 정보가 읽음(READ) 상태로 벌크 업데이트 적용
- 애플리케이션 로그 확인용으로 ExceptionHandler log 추가하였습니다.

Guttok 78 : 알림 상태 변경 API 구현

---

src/main/java/com/app/guttokback/global/apiResponse/ResponseMessages.java
src/main/java/com/app/guttokback/notification/controller/NotificationController.java
src/main/java/com/app/guttokback/notification/repository/NotificationQueryRepository.java
src/main/java/com/app/guttokback/notification/service/NotificationService.java
src/test/java/com/app/guttokback/notification/controller/NotificationControllerTest.java
src/test/java/com/app/guttokback/notification/repository/NotificationQueryRepositoryTest.java
src/test/java/com/app/guttokback/notification/service/NotificationServiceTest.java

[DELETE] /api/notifications
- 해당 api 요청 시 요청한 회원의 읽음(READ)상태의 알림 정보 벌크 삭제

Guttok 79 : 알림 삭제 API 구현

---

build.gradle
src/main/java/com/app/guttokback/GuttokBackApplication.java
src/main/java/com/app/guttokback/global/scheduler/SchedulerTask.java
src/main/java/com/app/guttokback/global/scheduler/config/SchedulerConfig.java

서비스 확장성을 고려하여 Scale-out 환경에서 Scheduler의 중복 실행을 방지하기 위해 Redis 분산락 기반의 Shedlock을 적용하였습니다.
```java
@SchedulerLock(name = "reminder", lockAtMostFor = "1h", lockAtLeastFor = "5m")
```
`lockAtMostFor`
- 락을 최대 1시간 유지하여, 만약 인스턴스가 비정상적으로 종료되더라도 최소 1시간 동안 다른 인스턴스가 같은 작업을 중복 실행하지 않도록 설정하였습니다.
`lockAtLeastFor`
- 최소 5분 동안 락을 유지하여, 작업이 빨리 끝나더라도 일정 시간 동안은 재실행을 방지하였습니다.
이 설정을 통해 여러 인스턴스가 실행되는 환경에서도 동일한 작업이 중복 수행되지 않도록 하였습니다.

Guttok 80 : Scheduler Shedlock 적용

---

src/main/java/com/app/guttokback/common/scheduler/SchedulerTask.java
src/main/java/com/app/guttokback/user/application/controller/UserController.java
src/main/java/com/app/guttokback/user/application/service/UserService.java

- 테스트 insert를 위한 Scheduler 주석처리
- 배포완료 이후 주석해제 예정
- ResponseData에 추가: User Alarm 수정 시 boolean 값으로 userAlarm을 리턴
- 단순히 true, false 값만 응답
ResponseBody
```json
{
"message": "알림 수정 성공",
"data": true,
"status": "OK"
}
```

Guttok 101 : User Alarm ResponseData 추가

---

src/main/java/com/app/guttokback/common/infrastructure/config/SecurityConfig.java

Spring security config에 cookieSerializer를 추가하여 
```
serializer.setSameSite("None");
serializer.setUseSecureCookie(true);
```
설정을 해줬습니다

GUTTOK-108 : secure: true, sameSite: 'none' 설정 추가

---

src/main/java/com/app/guttokback/common/infrastructure/config/SecurityConfig.java

```
.exceptionHandling(exception -> exception
.authenticationEntryPoint((request, response, authException) -> {
if (request.getSession(false) != null) {
request.getSession(false).invalidate();
}
response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
})
);
```
securityConfig에 위 코드를 적용해서 인증 실패 시 쿠키를 삭제 할 수 있도록 했습니다
인증 실패 했는데 쿠키가 생성되었던 이유는 "Spring Security 확인 -> 인증 없음 -> 예외 처리 및 인증 흐름 시도 -> SecurityContext 저장 필요로 인해 세션 생성됨" 의 흐름이 발생해 쿠키가 생성됐던 것입니다

GUTTOK-109 : 인증 실패 시 쿠키 삭제

---

src/main/java/com/app/guttokback/user/domain/entity/User.java

```
// user entity 수정 전
@Table(name = "USERS")
@SQLDelete(sql = "UPDATE USERS SET deleted = true WHERE id = ?")
```
```
// user entity 수정 후
@Table(name = "users")
@SQLDelete(sql = "UPDATE users SET deleted = true WHERE id = ?")
```
aws ec2 운영체제인 우분투에서 대소문자 구문이 된다고 합니다
로컬 환경에서는 구분을 안하고 동작해서 로컬 테스트에서 오류 없이 동작했던것 같습니다.
다른 해결 방법으로는 리눅스의 기본 설정을 바꾸는 방법입니다
```
// 변경 전
lower_case_table_names = 0
// 변경 후
lower_case_table_names = 1
```
리눅스의 기본 설정을 바꾸면 DB 서버 전체에 영향을 줘서, 충돌, 마이그레이션 문제 등 유발 가능성이 크다고 합니다

GUTTOK-113 : AWS 회원 탈퇴 오류 수정

---

src/main/java/com/app/guttokback/user/application/controller/UserController.java

```
HttpSession session = request.getSession(false);
if (session != null) {
session.invalidate();
}
Cookie[] cookies = request.getCookies();
if (cookies != null) {
for (Cookie cookie : cookies) {
if ("SESSION".equals(cookie.getName())) {
cookie.setMaxAge(0);
cookie.setPath("/");
response.addCookie(cookie);
}
}
}
```
을 추가하여 쿠키를 삭제하도록 했습니다

GUTTOK-114 : 회원 탈퇴 시 쿠키 삭제

---

src/main/java/com/app/guttokback/common/infrastructure/config/SecurityConfig.java
src/main/java/com/app/guttokback/common/scheduler/SchedulerTask.java
src/main/java/com/app/guttokback/common/security/Roles.java
src/main/java/com/app/guttokback/user/application/controller/UserController.java
src/main/java/com/app/guttokback/user/application/service/TestAccountResetService.java
src/main/java/com/app/guttokback/user/application/service/UserService.java
src/main/java/com/app/guttokback/user/domain/repository/UserRepository.java

ROLE_TEST 이라는 테스트 권한을 추가했습니다
테스트 계정은 한번만 추가하면 된다고 생각해서 서버에서 직접 권한을 ROLE_USER 에서 ROLE_TEST 로 바꾸려고 합니다
```
// UserRepository
@Query("SELECT u FROM User u WHERE :role MEMBER OF u.roles")
List<User> findTestAccounts(@Param("role") Roles role);
```
user repository에 권한 조회 쿼리를 추가해서 ROLE_TEST 을 찾을 수 있도록 했습니다
user 패키지에 TestAccountResetService 클래스를 만들어서 ROLE_TEST을 조회해 스케줄러가 동작한는 코드를 추가했습니다
```
@Transactional
public void resetTestAccounts() {
List<User> testUsers = userRepository.findTestAccounts(Roles.ROLE_TEST);
for (User user : testUsers) {
/*이메일 발송횟수, 구독항목 주기 삭제*/
}
}
```

Guttok-116 : 테스트 계정 권한 추가

---

src/main/java/com/app/guttokback/common/converter/EnumConverter.java
src/main/java/com/app/guttokback/email/application/service/EmailLogService.java
src/main/java/com/app/guttokback/email/application/service/ReminderService.java
src/main/java/com/app/guttokback/email/domain/entity/EmailLog.java
src/main/java/com/app/guttokback/email/domain/enums/EmailType.java
src/main/java/com/app/guttokback/email/domain/repository/EmailLogRepository.java
src/main/java/com/app/guttokback/user/application/service/TestAccountResetService.java
src/main/java/com/app/guttokback/user/application/service/UserService.java

테스트 계정에 대한 리마인더 이메일 발송 처리하였습니다.
- 유저 권한이 ROLE_TEST 일 시
- 이메일을 발송하지 않음
- 알림 저장 및 reminderDate 갱신은 기존과 동일하게 수행
- 이메일 발송에 대한 추적 로그 테이블 추가
- 저장 값 : `id(PK)`, `user_id(FK)`, `email_type`, `count`, `register_date`, `update_date`
- 최초 이메일 발송 시 count를 1로 저장
- 이후 동일 유형의 이메일 발송 시 count를 1씩 증가
- emailType으로 이메일 유형을 관리

Guttok 118 : 테스트 계정 리마인더 발송 처리
